# Aegis OS — LightDM GTK greeter appearance
[greeter]
theme-name = adw-gtk3-dark
icon-theme-name = Papirus-Dark
font-name = Noto Sans 11
background = /usr/share/backgrounds/aegis/aegis-wallpaper.svg
user-background = false
default-user-image = #dialog-password
xft-antialias = true
xft-hintstyle = hintslight
xft-rgba = rgb
indicators = ~host;~spacer;~clock;~spacer;~session;~power
clock-format = %a %d %b  %H:%M
position = 50%,center 55%,center
