# Aegis OS — bootloader (GRUB, BIOS + UEFI)
---
efiBootLoader: "grub"
kernel: "/vmlinuz-linux"
img: "/initramfs-linux.img"
fallback: "/initramfs-linux-fallback.img"
timeout: "5"
bootloaderEntryName: "Aegis OS"
efiBootloaderId: "AegisOS"
kernelParams: [ "quiet" ]
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true
