# Aegis OS — user account creation
---
defaultGroups:
  - wheel
  - network
  - video
  - audio
  - storage
  - optical
  - power
  - input
  - lp
  - scanner
  - sys
  - rfkill
  - uucp
autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: true
doReusePassword: false
availableShells: /usr/bin/zsh, /bin/bash
userShell: /usr/bin/zsh
passwordRequirements:
  minLength: 4
  maxLength: -1
